Repository RakambdaOrg/ChannelPointsMiner, pull requests merged in 2024-10, with the labels that each got.

#890 Fix log4j2 error when launching app from shaded jar
  .github/ISSUE_TEMPLATE/0_bug_report.yml
  .github/ISSUE_TEMPLATE/1_feature_request.yml
  miner/build.gradle.kts
Labels: type: 🐛 bug

#901 🔄 synced file(s) with RakambdaOrg/rakambda-github-files
  .github/dependabot.yml
Labels: sync

#905 Automatically detect dismissible site-wide drops campaigns
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/DropCampaignSummary.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfo.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiDropsHighlightServiceAvailableDropsTest.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfoTest.java
  miner/src/test/resources/api/gql/gql/dropsHighlightServiceAvailableDrops_withDrops.json
Labels: type: 🧱 enhancement, app: ⛏️ miner
