Repository RakambdaOrg/ChannelPointsMiner, pull requests merged in 2024-05, with the labels that each got.

#772 🔄 synced file(s) with RakambdaOrg/rakambda-github-files
  .github/dependabot.yml
Labels: sync

#774 New method to progress drops
  .github/workflows/manual-docker.yml
  gradle/libs.versions.toml
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApi.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/playbackaccesstoken/PlaybackAccessTokenData.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/playbackaccesstoken/PlaybackAccessTokenOperation.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/GQLType.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/StreamPlaybackAccessToken.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApi.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/subtype/Summary.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/factory/MinerRunnableFactory.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/miner/Miner.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendM3u8MinutesWatched.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendMinutesWatched.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendSpadeMinutesWatched.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfo.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/streamer/Streamer.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApiPlaybackAccessTokenTest.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApiTest.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/factory/MinerRunnableFactoryTest.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/SendM3u8MinutesWatchedTest.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/SendMinutesWatchedTest.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/SendSpadeMinutesWatchedTest.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfoTest.java
  miner/src/test/resources/api/gql/gql/playbackaccesstoken_success.json
Labels: type: 🐛 bug, app: ⛏️ miner

#779 🔄 synced file(s) with RakambdaOrg/rakambda-github-files
  .github/dependabot.yml
Labels: sync

#785 Do not make m3u8 requests if streamer does not activate drops
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendM3u8MinutesWatched.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendMinutesWatched.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/SendSpadeMinutesWatched.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfo.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/runnable/UpdateStreamInfoTest.java
Labels: type: 🧱 enhancement, app: ⛏️ miner

#790 🔄 synced file(s) with RakambdaOrg/rakambda-github-files
  .github/dependabot.yml
Labels: sync
