Repository RakambdaOrg/ChannelPointsMiner, pull requests merged in 2024-06, with the labels that each got.

#795 Migrate to latest Java LTS (21) to get latest performance improvments and security fixes + run Java 22 in docker image + hopefully fix memory leak issue when drops are enabled
  .github/workflows/analyse.yml
  miner/build.gradle.kts
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/discord/DiscordApi.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/GQLApi.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/gql/data/types/StreamPlaybackAccessToken.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/gql/integrity/http/NoIntegrityProvider.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/passport/http/HttpLoginProvider.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/telegram/data/Message.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApi.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/TwitchPubSubWebSocketClient.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/createnotification/Notification.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/eventcreated/EventCreatedData.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/predictionmade/PredictionMadeData.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/predictionupdated/PredictionUpdatedData.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/subtype/Claim.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/subtype/PointGain.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/ws/data/message/subtype/Predictor.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/factory/ApiFactory.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/factory/TwitchChatFactory.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/runnable/StreamerConfigurationReload.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/util/json/URLDeserializer.java
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/util/json/UnknownDeserializer.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApiTest.java
  viewer/build.gradle.kts
Labels: app: 👀 viewer, app: ⛏️ miner, type: ⚙️ internal enhancement

#802 Improve M3U8 request by performing head request
  miner/src/main/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApi.java
  miner/src/test/java/fr/rakambda/channelpointsminer/miner/api/twitch/TwitchApiTest.java
Labels: app: ⛏️ miner, type: ⚙️ internal enhancement

#805 🔄 synced file(s) with RakambdaOrg/rakambda-github-files
  .github/dependabot.yml
  .github/renovate.json
Labels: sync

#808 🔄 synced file(s) with RakambdaOrg/rakambda-github-files
  .github/renovate.json
Labels: sync

#813 🔄 synced file(s) with RakambdaOrg/rakambda-github-files
  .github/dependabot.yml
Labels: sync
